# Generated by Django 5.0 on 2023-12-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_time_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
